### PR TITLE
Upgrade dependencies. Move from webjars-locator to webjars-locator-core

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by mkurz** [comment]
There is v32 now.

**Comment by benmccann** [comment]
I don't really have time at the moment to update this PR. It wouldn't hurt to merge anyway since it's still an improvement and we can always further upgrade the libraries

**Comment by huntc** [comment]
Is there a burning issue to be resolved by updating? Always nice to stay up to date, but not necessarily essential.

**Comment by benmccann** [comment]
I think there was some issue that this fixed. It was so long ago I can't really remember now. I was spending a bit of time trying to get server side js rendering and mochajs testing working for our project before abandoning it for other work.

**Comment by benmccann** [comment]
@huntc @mkurz would you be able to give this one another look? thanks

**Comment by huntc** [comment]
@benmccann Do you want a new release?

**Comment by benmccann** [comment]
That would be great! James had two PRs pending for this project that might be good to merge as well first. One of them looked like it might help in the release process

**Pull request merged**
